Idan-local
idandagan1/MyStreet pull request #4
Opened 2017-01-13 20:43 UTC by idandagan1

Added search street to header, changed some naming conventions.

2017-01-14 12:52 UTC, idandagan1 commented on client/actions/user-action-creators.js
> +export default function facebookLoginSubmitted(user) {
Ignore this

2017-01-15 15:38 UTC, slenrow commented on client/actions/user-action-creators.js
> +export default function facebookLoginSubmitted(user) {
This is breaking the facebook login. When you exporting `default` only exports that  one thing from a file. I'm guessing your linter was yelling at you to change this? All action-creator files will have multiple exports, so this warning you can always ignore when you're in an action creator file or a file that you know will have many exported functions.

2017-01-15 15:46 UTC, idandagan1 commented on client/actions/user-action-creators.js
> +export default function facebookLoginSubmitted(user) {
You are absolutely right! that's why I told you to ignore it lol

2017-01-15 16:12 UTC, slenrow commented
Good job @idandagan1. Just some small things to fix.

2017-01-15 18:44 UTC, slenrow requested changes

2017-01-15 18:44 UTC, slenrow commented on client/components/google-search/google-search.js
> +        this.handleSearchClicked = this.handleSearchClicked.bind(this);
This is unnecessary since `handleSearchClicked` is an arrow function. `this` is always automatically bound to arrow functions.

2017-01-15 18:44 UTC, slenrow commented on client/views/app-layout/app-layout/app-layout.js
> +import React, { PropTypes } from 'react';
What's this file for? This is a duplicate of `app-layout-connector.js`

2017-01-15 18:44 UTC, slenrow commented on client/views/app-layout/state/app-layout-action-types.js
> +export default createActionTypes('HEADER', [
This prefix should be `'APP_LAYOUT'`

2017-01-15 18:44 UTC, slenrow commented on client/views/header/components/header.js
> +function Header(props) {
NICE. Functional components for the win! One note is that you can move the `export default` line at the bottom of the file inline here: `export default function Header(props)`

2017-01-15 18:44 UTC, slenrow commented on client/views/header/components/header.js
>  import React, { Component, PropTypes } from 'react';
You can remove the unused `Component` dependency since you changed it to a functional component.

2017-01-15 18:44 UTC, slenrow commented on client/views/app-layout/state/app-layout-action-creators.js
> +}
I definitely agree with moving login related actions into the app-wide state. Good looks.

2017-01-15 18:44 UTC, slenrow commented on client/views/my-streets/components/my-streets.js
> +        this.onJoinClick = this.onJoinClick.bind(this);
This is unnecessary if you turn `onJoinClick` into an arrow function.

2017-01-15 18:44 UTC, slenrow commented on client/views/my-streets/components/my-streets.js
> +    onJoinClick() {
Make this an arrow function. Typically, any event handler will be an arrow function.

2017-01-15 18:44 UTC, slenrow commented on client/views/my-streets/components/my-streets.js
> +            isMember: false,
All of this local state will likely need to go into redux state eventually.

2017-01-16 10:51 UTC, closed without merging